swagger: "2.0"
info:
  title: "Nama App"
  version: "1.0.0"
  description: "Ini sebuah aplikasi"
  
tags:
- name: "Article"
  description: "Article resources"

paths:
  /articles:
    get:
      tags:
      - "Article"
      summary: "List all available articles"
      description: "Description for list article"
      produces:
      - "application/json"
      responses: 
        "200":
          description: "Success"
          schema: 
            type: "array"
            items:
              type: "object"
              properties: 
                id: 
                  type: "integer"
                  example: 1
                title:
                  type: "string"
                  example: "Lorem ipsum"
                body:
                  type: "string"
                  example: "Dolor sit amet"
    
    post: 
      tags:
      - "Article"
      summary: "Add new article"
      description: "Create new"
      security:
      - Token: []
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Article object"
        required: true
        schema: 
          type: "object"
          properties: 
            title:
              type: "string"
              example: "Lorem ipsum"
            body:
              type: "string"
              example: "Dolor sit amet"
      produces: 
      - "application/json"
      responses:
        "201":
          description: "Succesfully create new article"
          schema:
            type: "object"
            properties:
              id: 
                type: "integer"
                example: 1
              title:
                type: "string"
                example: "Lorem Ipsum"
              body: 
                type: "string"
                example: "Dolor sit amet"
  /articles/{articleId}:
    get:
      tags:
      - "Article"
      summary: "Find article by ID"
      description: "Returns a single Article"
      parameters:
      - in: "path"
        name: "articleId"
        description: "ID of article to return"
        required: true
        type: "integer"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                example: 1
              title: 
                type: "string"
                example: "Lorem Ipsum"
              body:
                type: "string"
                example: "Dolor sit amet"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Article not found"
          
securityDefinitions:
  Token:
    type: "apiKey"
    in: "header"
    name: "Authorization"